[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qtools"
version = "0.1.0"
description = "Python tools for quantitative analysis"
requires-python = ">=3.10"
dependencies = []

